version: '3.9'

services:
  nginx:
    image: nginx:alpine 
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./frontend:/usr/share/nginx/html 
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "8080"  
    volumes:
      - ./backend/Task:/app/Task
      - ./backend/course:/app/course
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
